[package]
name = "I3M-Engine-Core"
version = "0.17.0"
license = "MIT"
authors = ["Dedan Okware <softengdedan@gmail.com>"]
edition = "2021"
rust-version = "1.72"
description = "A standalone scene editor for Fyrox game engine"
homepage = "https://github.com/IThreeM/I3M-Engine-Core"
keywords = ["fyrox", "editor", "rust"]
repository = "https://github.com/IThreeM/I3M-Engine-Core"
readme = "README.md"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]

[dependencies]
fyrox = { version = "0.34.0", path = "../fyrox" }
I3M-Engine-Core_base = { version = "0.21.0", path = "../editor" }
clap = { version = "4", features = ["derive"] }
