[package]
name = "I3M-Project-Manager"
version = "1.0.0"
edition = "2021"

[dependencies]
i3m = { path = "../i3m" }
I3M-CLI-core = { version = "0.1.0", path = "../template-core" }
serde = { version = "1", features = ["derive"] }
ron = "0.8.1"
open = "5.0.1"