[package]
name = "fyrox-animation"
version = "0.2.0"
authors = ["Dedan Okware <softengdedan@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Flexible Animation System"
keywords = ["animation", "game"]
categories = ["game-development", "animation"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
homepage = "https://ithreem.com"
documentation = "https://docs.rs/fyrox-animation"
repository = "https://github.com/IThreeM/I3M-Engine-Core"
readme = "README.md"
rust-version = "1.72"

[dependencies]
i3m-core = { version = "0.28.1", path = "../i3m-core" }
strum = "0.26.1"
strum_macros = "0.26.1"
fxhash = "0.2.1"
spade = "2.1.0"