name: IThreeM CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  tests:
    name: Tests IThreeM-CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2

      - name: Install linux deps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libasound2-dev libudev-dev pkg-config xorg-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev

      - run: rustc --version && cargo --version

      - name: Build and test
        env:
          RUSTFLAGS: -C prefer-dynamic=yes
        run: |
          cargo build --verbose --workspace --all-targets --all-features --profile github-ci
          cargo test --verbose --workspace --all-features --profile github-ci

  wasm:
    name: Wasm IThreeM-CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2

      - run: rustc --version && cargo --version
      - name: Build
        run: |
          cargo build --verbose --target=wasm32-unknown-unknown --package i3m

  format:
    name: Rustfmt IThreeM-CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo fmt --version
      - run: cargo fmt -- --check

  clippy:
    name: Clippy IThreeM-CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install linux deps
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libasound2-dev libudev-dev pkg-config xorg-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev

      - run: cargo clippy --version
      - run: cargo clippy --workspace --all-targets --all-features -- --deny warnings

  docs:
    name: Documentation IThreeM-CI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2

      - run: rustc --version && cargo --version
      - name: Build Docs
        run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: --deny warnings

  template_pc:
    name: Project Template (PC)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Tools
        run: |
          cargo install I3M-CLI --path=template --force
      - name: Generate and Build Projects
        run: |
          cd ../
          I3M-CLI init --name test_project --style=3d
          cd test_project
          I3M-CLI upgrade --version=latest --local
          cargo build --package editor

  template_android:
    name: Project Template (Android)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 10406996
      - run: sdkmanager tools "platforms;android-30"
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26
      - name: Install Tools
        run: |
          cargo install I3M-CLI --path=template --force
          cargo install cargo-apk
          rustup target add armv7-linux-androideabi
      - name: Generate and Build Projects
        run: |
          cd ../
          I3M-CLI init --name test_project --style=3d
          cd test_project
          I3M-CLI upgrade --version=latest --local
          cargo-apk apk build --package executor-android --target armv7-linux-androideabi

  template_wasm:
    name: Project Template (WASM)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Tools
        run: |
          cargo install I3M-CLI --path=template --force
          cargo install wasm-pack
          rustup target add wasm32-unknown-unknown
      - name: Generate and Build Projects
        run: |
          cd ../
          I3M-CLI init --name test_project --style=3d
          cd test_project
          I3M-CLI upgrade --version=latest --local
          cd executor-wasm
          wasm-pack build --target=web

  release_pc:
    name: Release Editors (PC)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build I3M-Engine-Core
        run: cargo build --release --package I3M-Engine-Core

      - name: Build i3m_engine_core_base
        run: cargo build --release --package i3m_engine_core_base

      - name: Upload I3M-Engine-Core Artifact
        uses: actions/upload-artifact@v3
        with:
          name: I3M-Engine-Core-${{ matrix.os }}
          path: target/release/I3M-Engine-Core

      - name: Upload i3m_engine_core_base Artifact
        uses: actions/upload-artifact@v3
        with:
          name: i3m_engine_core_base-${{ matrix.os }}
          path: target/release/i3m_engine_core_base
