name: Publish Crates

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Log in to crates.io
      run: echo ${{ secrets.CARGO_REGISTRY_TOKEN }} | cargo login

    - name: Publish all crates
      run: |
        # Iterate over each Cargo.toml file in the workspace
        for crate in $(find . -name Cargo.toml); do
          # Get the crate name and version
          CRATE_NAME=$(grep -E '^name\s*=' $crate | sed -E 's/name\s*=\s*"([^"]+)"/\1/')
          VERSION=$(grep -E '^version\s*=' $crate | sed -E 's/version\s*=\s*"([^"]+)"/\1/')

          # Check if the crate version is already published
          if cargo search $CRATE_NAME --limit 1 | grep -q $VERSION; then
            echo "$CRATE_NAME v$VERSION is already published. Skipping."
          else
            # Attempt to publish the crate
            cargo publish --manifest-path $crate || echo "Failed to publish $CRATE_NAME v$VERSION"
          fi
        done
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
